---
- name: configure ODBC in res_odbc.conf
  ini_file:
   dest: "/etc/asterisk/res_odbc.conf"
   section: "asterisk"
   option: "{{ item.option }}"
   value: "{{ item.value }}"
  with_items:
    - { option: "enabled", value: "yes"}
    - { option: "dsn", value: "asterisk-connector"}
    - { option: "username", value:  '{{iasterisk_odbc_user}}'}
    - { option: "password", value:  '{{iasterisk_odbc_password}}'}
  # - { option: "max_connections", value: "1" }
    - { option: "pre-connect", value: "yes" }

