---
- name: Asterisk | copy conf files
  file:
    src: /var/www/html/alotim/asterisk/{{ item }}.conf
    dest: /etc/asterisk/{{ item }}.conf
    backup: true
    owner: asterisk
    group: asterisk
  become: true
  with_items: "{{ asterisk_config_files }}"
  notify: Restart asterisk
