---
- name: Install epel
  yum: "pkg=epel-release state=installed"

- name: Install asterisk pre-requisites via yum
  yum:
    name: "{{asterisk_source_dep}}"
    state: present

- name: Install useful tools via yum
  yum:
    name: "{{asterisk_tools}}"
    state: present
