---

- name: Make temp pjproject dir
  file: "path=/tmp/pjproject state=directory"

- name: Download and extract pjSIP source
  unarchive: "src=http://www.pjsip.org/release/2.4.5/pjproject-2.4.5.tar.bz2 dest=/tmp/pjproject/ remote_src=yes extra_opts=--strip-components=1"

- name: Build pjsip from tarball
  command: "{{ item }} chdir=/tmp/pjproject/"
  with_items:
    - ./configure --prefix=/usr --libdir=/usr/lib64 --enable-shared --disable-sound --disable-resample --disable-video --disable-opencore-amr
    - make dep
    - make
    - make install
    - ldconfig